version: "3.9"

services:
  aut-api-mainnet:
    container_name: aut-api-mainnet
    image: node:21.1.0
    build:
      context: .
      dockerfile: Dockerfile.mainnet
    working_dir: /app
    environment:
      - SERVER_PORT=4008
      - NODE_ENV=production
      - MONGODB_CONNECTION_STRING=mongodb://aut-db-mainnet:27017
    ports:
      - "4008:4008"
    depends_on:
      - aut-db-mainnet
    deploy:
      restart_policy:
        condition: on-failure

  aut-db-mainnet:
    container_name: aut-db-mainnet
    image: mongo
    volumes:
      - mongodata_mainnet:/data/db
    ports:
      - "27019:27017"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongodata_mainnet:
