version: '3.9'

services:
  aut-api:
    container_name: aut-api
    image: node:16
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENVIRONMENT_IP=localhost
      - SERVER_PORT=4005
      - NODE_ENV=development
    ports:
      - "4005:4005"
    networks:
      - aut-api
    depends_on:
      - aut-db
    deploy:
      restart_policy:
        condition: on-failure

  # aut-db:
  #   container_name: aut-db
  #   image: mongo
  #   volumes:
  #     - mongodata:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - aut-api
  #   deploy:
  #     restart_policy:
  #       condition: on-failure

volumes:
  mongodata:

networks:
  aut-api:
    driver: bridge

