version: "3.9"

services:
  aut-api-testnet:
    container_name: aut-api-testnet
    image: node:21.1.0
    build: .
    environment:
      - SERVER_PORT=4007
      - NODE_ENV=production
      - MONGODB_CONNECTION_STRING=mongodb://aut-db-testnet:27017
    ports:
      - "4007:4007"
    depends_on:
      - aut-db-testnet
    deploy:
      restart_policy:
        condition: on-failure

  aut-db-testnet:
    container_name: aut-db-testnet
    image: mongo
    volumes:
      - mongodata_testnet:/data/db
    ports:
      - "27018:27017"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongodata_testnet:
