version: "3.9"

services:
  aut-api-prod:
    container_name: aut-api-prod
    image: node:21.1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENVIRONMENT_IP=localhost
      - SERVER_PORT=4005
      - NODE_ENV=development
    ports:
      - "4006:4005"
    depends_on:
      - aut-db-prod
    deploy:
      restart_policy:
        condition: on-failure

  aut-db-prod:
    container_name: aut-db-prod
    image: mongo
    volumes:
      - mongodataprod:/data/db
    ports:
      - "27018:27017"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongodataprod:
